<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.1" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EcoCoinSharedTypes\EcoCoinSharedTypes.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="GenericDataAccessClassCore">
      <HintPath>..\Libs\GenericDataAccessClassCore.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Data.SqlClient">
      <HintPath>..\Libs\Microsoft.Data.SqlClient.dll</HintPath>
    </Reference>
    <Reference Include="System.Data.Odbc">
      <HintPath>..\Libs\System.Data.Odbc.dll</HintPath>
    </Reference>
    <Reference Include="System.Data.OleDb">
      <HintPath>..\Libs\System.Data.OleDb.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
