<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EcoCoinSharedTypes\EcoCoinSharedTypes.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="GenericDataAccessClassCore">
      <HintPath>..\Libs\GenericDataAccessClassCore.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="appconfig.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
